### PR TITLE
Print best value first, then anything else. Sort by lowset pixel offset

### PR DESCRIPTION
**Pull request by CyberAP**
Also did a small refactor. Hope you don't mind.

### CODE REVIEW

**Comment by CyberAP** [comment]
Allowed offset needs further investigation. How much offset can we allow?

**Comment by alexzaworski** [comment]
It needs to be relative to the conversion, eg `mm` can be further from an exact match than `em`

Maybe for now the resulting difference has to be <= 1.5px? Or round to a pixel?

For the example 325px:

86mm (exact is 86.3mm) is accepted, since 0.3mm is ~1.16px

20em (exact 20.3em) is not accepted, since .3 em is ~4.8px

**Comment by alexzaworski** [comment]
Ah you've basically implemented exactly what I described, results seem good. I say we test some stuff but shoot for 1.5 as the allowed difference

**Comment by CyberAP** [comment]
This is not yet finished. I've found out that some values are floating points, when they could be fixed numbers. Working on a patch.

**Comment by alexzaworski** [comment]
```
➜  unit-golfer git:(CyberAP-patch-1) node unit-golf 325

Best: 340q, offset by: 3.859375 pixels

Rest:
81vw (offset: 1)
45ex (offset: 2.3)
20em (offset: 5)
86mm (offset: 1.2)
8.6cm (offset: 0.081)
110vh (offset: 5)
240pt (offset: 6.3)
3.4in (offset: 1.4)
330px (offset: 5)
```
We should verify px widths for mm/cm since the difference there is strange (though maybe correct)

Here are the results using these values:

- `86mm` ok
- `8.6cm` ok
- `1.4in` nope
- `81vw` nope

This is very hard to create rules for since `86mm` should be further off than `81vw` no?

**Comment by alexzaworski** [comment]
More findings:

div of width `1mm` has a width of `3.765625px`
div of width `10mm` has a width of `37.78125px`
div of width `86mm` has a width of `325.03125px` (our offset is way off here)

So perhaps the actual allowed variance is much smaller than 1px

**Comment by alexzaworski** [comment]
More science: up to `325.96px` was accepted, maybe the allowance is `.04px`?

**Comment by CyberAP** [comment]
Set max offset to .5, max precision to 2 digits. Configurable via arguments. Results are now much better.

**Comment by alexzaworski** [comment]
Looks pretty solid, should work for like 90% of cases if not more

I have some ideas to make this more stable but for now I don't see any reason to not merge this, thank you!

**Pull request merged**
